import type { Page } from '@playwright/test';
import type { StockPoolItem, GateResult, AnalysisReport } from '../../src/types';

// ── Stock Pool Mock Data ──────────────────────────────────

export const stockPoolMock: StockPoolItem[] = [
  {
    ts_code: '600519.SH',
    name: '贵州茅台',
    industry: '白酒',
    pr: 6.52,
    pe: 28.3,
    pb: 8.2,
    dividend_yield: 2.1,
    market_cap: 2100000000000,
    cq_passed: true,
    pr_passed: true,
    has_report: true,
    scores: {
      Q1_business: 8,
      Q2_moat: 9,
      Q3_growth: 7,
      R1_environment: 6,
      R2_management: 8,
      R3_control: 7,
      V1_value_trap: 8,
      V2_percentile: 5,
      V3_stress_test: 7,
      total: 7.2,
      Q_weighted: 8.0,
      R_weighted: 7.0,
      V_weighted: 6.7,
    },
  },
  {
    ts_code: '002415.SZ',
    name: '海康威视',
    industry: 'IT设备',
    pr: 4.20,
    pe: 22.1,
    pb: 4.5,
    dividend_yield: 1.8,
    market_cap: 350000000000,
    cq_passed: false,
    pr_passed: false,
    has_report: false,
  },
  {
    ts_code: '000651.SZ',
    name: '格力电器',
    industry: '家电',
    pr: 7.85,
    pe: 9.2,
    pb: 2.1,
    dividend_yield: 5.3,
    market_cap: 230000000000,
    cq_passed: true,
    pr_passed: true,
    has_report: true,
    scores: {
      Q1_business: 7,
      Q2_moat: 6,
      Q3_growth: 4,
      R1_environment: 5,
      R2_management: 7,
      R3_control: 8,
      V1_value_trap: 9,
      V2_percentile: 8,
      V3_stress_test: 8,
      total: 6.8,
      Q_weighted: 5.7,
      R_weighted: 6.7,
      V_weighted: 8.3,
    },
  },
  {
    ts_code: '002555.SZ',
    name: '三七互娱',
    industry: '游戏',
    pr: 8.10,
    pe: 15.6,
    pb: 2.8,
    dividend_yield: 4.2,
    market_cap: 55000000000,
    cq_passed: true,
    pr_passed: true,
    has_report: false,
  },
];

// ── Gate Result Mock ─────────────────────────────────────

function makeGate(cqPassed: boolean): GateResult {
  return {
    cash_quality: {
      overall_passed: cqPassed,
      failed_dimensions: cqPassed ? [] : [3],
      dimension_1_opcf_to_netprofit: { passed: true, avg_3y: 1.15 },
      dimension_2_fcf_positive_years: { passed: true, positive_count: 5 },
      dimension_3_receivables_ratio: {
        passed: cqPassed,
        avg_3y: cqPassed ? 0.08 : 0.35,
      },
      dimension_4_inventory_stability: { passed: true, cv: 0.12 },
      dimension_5_ocf_stability: { passed: true, cv: 0.09 },
    },
    penetration_return: {
      pr_result: { pr: 6.52, risk_free_rate: 2.5, threshold: 5.0, passed: true },
      disposable_cash: { disposable_cash: 50000000000 },
      distribution_ratio: { ratio: 0.51 },
      repurchase: { avg_repurchase_3y: 2000000000 },
    },
    qrv_summary: '基本面优秀，现金流健康，穿透回报率达标。',
    scores: {
      Q1_business: 8,
      Q2_moat: 9,
      Q3_growth: 7,
      R1_environment: 6,
      R2_management: 8,
      R3_control: 7,
      V1_value_trap: 8,
      V2_percentile: 5,
      V3_stress_test: 7,
      total: 7.2,
      Q_weighted: 8.0,
      R_weighted: 7.0,
      V_weighted: 6.7,
    },
  };
}

export function gateMock(cqPassed = true): GateResult {
  return makeGate(cqPassed);
}

// ── Analysis Report Mock ─────────────────────────────────

const REPORT_MD = [
  '## QRV 综合打分卡',
  '',
  '| 维度 | 得分 | 权重 |',
  '|------|------|------|',
  '| Q1 生意本质 | 8.0 | 25% |',
  '| Q2 护城河 | 9.0 | 25% |',
  '| Q3 增长引擎 | 7.0 | 25% |',
  '| R1 外部环境 | 6.0 | 10% |',
  '| R2 管理层 | 8.0 | 10% |',
  '| R3 控股结构 | 7.0 | 10% |',
  '| V1 价值陷阱 | 8.0 | 33% |',
  '| V2 历史分位 | 5.0 | 33% |',
  '| V3 压力测试 | 7.0 | 33% |',
  '| **总分** | **7.2** | — |',
  '',
  '## 生意本质与商业模式',
  '',
  '贵州茅台主营业务为茅台酒及系列酒的生产与销售，是国内高端白酒绝对龙头。',
  '',
  '### 收入分析',
  '',
  '| 年份 | 营业收入(亿) | 同比 | 毛利率 |',
  '|------|-------------|------|--------|',
  '| 2021 | 1094 | 11.7% | 91.6% |',
  '| 2022 | 1276 | 16.5% | 92.0% |',
  '| 2023 | 1506 | 18.0% | 92.1% |',
  '',
  '### PASS/FAIL 判定',
  '',
  '| 指标 | 结果 | 说明 |',
  '|------|------|------|',
  '| 经营现金流/净利润 > 0.8 | PASS | 近三年均值为 1.15 |',
  '| 自由现金流为正年数 >= 4 | PASS | 近5年均为正 |',
  '| 应收账款占比 < 30% | PASS | 仅为 8% |',
  '',
  '## 护城河与竞争壁垒',
  '',
  '茅台拥有极强的品牌护城河，具有定价权。白酒行业存在天然地域壁垒。',
  '',
  '<h3>竞争格局</h3>',
  '',
  '茅台在高端白酒市场市占率超过 60%。',
  '',
  '## 增长引擎',
  '',
  '### 量价驱动',
  '',
  '增长主要来自两方面：1）直销比例提升带来的均价上行；2）系列酒产能扩张。',
  '',
  '<h3>第二曲线</h3>',
  '',
  'i茅台数字营销平台贡献约 20% 营收增量。',
  '',
  '## 风险因素',
  '',
  '主要风险包括：消费税改革、反腐政策影响、白酒消费结构变化。',
  '',
  '## 参考来源',
  '',
  '| 来源 | 内容 |',
  '|------|------|',
  '| 年报2023 <cite data-ref="REF001" id="cite-REF001">[REF001]</cite> | 2023年年度报告，第45-89页 |',
  '| Tushare数据 <cite data-ref="REF002" id="cite-REF002">[REF002]</cite> | 近5年财务数据 |',
  '| 行业研报 <cite data-ref="REF003" id="cite-REF003">[REF003]</cite> | 券商行业研究报告 |',
  '',
  '## 综合研判与建议',
  '',
  '综合各维度评估，贵州茅台 QRV 总分为 7.2/10。',
  '',
].join('\n');

export const reportMock: AnalysisReport = {
  ts_code: '600519.SH',
  name: '贵州茅台',
  report_markdown: REPORT_MD,
};
